analyzer:
  working-dir: .
  allowDynamicVersions: true

scanner:
  license:
    allow:
      - MIT
      - Apache-2.0
      - BSD-3-Clause
    deny:
      - GPL-2.0-only
      - GPL-3.0-only
      - AGPL-3.0-only
      - LGPL-2.1-only
      - LGPL-3.0-only
    fail-on:
      licenses: deny

advisor:
  advisory:
    severity-threshold: medium

excludes:
  paths:
    - pattern: 'docs/.vite/deps/**'
      reason: 'BUILD_TOOL_OF'
      comment: 'Ignore Vite-generated dependency folder'
