analyzer:
  allow_dynamic_versions: true
  skip_excluded: true

excludes:
  paths:
    - pattern: '@iavofficial/**'
      reason: 'BUILD_TOOL_OF'
      comment: 'Ignore internal packages'
  paths:
    - pattern: 'docs/.vite/deps/**'
      reason: 'BUILD_TOOL_OF'
      comment: 'Ignore Vite-generated dependency folder'