analyzer:
  allow_dynamic_versions: true
  skip_excluded: true
  workspace_handling: IGNORE

excludes:
  paths:
    - pattern: 'docs/.vite/deps/**'
      reason: 'BUILD_TOOL_OF'
      comment: 'Ignore Vite-generated dependency folder'
