analyzer:
  allow_dynamic_versions: true
  skip_excluded: true
  ignore:
    projects:
      - '@iavofficial/frontend-framework-aws-authenticator'
      - '@iavofficial/frontend-framework-shared'

excludes:
  paths:
    - pattern: 'docs/.vite/deps/**'
      reason: 'BUILD_TOOL_OF'
      comment: 'Ignore Vite-generated dependency folder'
