analyzer:
  packageManagers:
    NPM:
      resolveScopes: false
      ignoreDevDependencies: true
  allowDynamicVersions: true
  skipExcluded: true

excludes:
  paths:
    - pattern: 'docs/.vite/deps/**'
      reason: 'BUILD_TOOL_OF'
      comment: 'Ignore Vite-generated dependency folder'
