name: 🐞 Bug Report
description: Create a report to help us improving the Frontend Framework.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summarize the encountered bug concisely.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Framework version
      description: For which version of the Frontend Framework you want to report the bug?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can one reproduce the issue - this is very important.
    validations:
      required: true
  - type: textarea
    id: currentBehavior
    attributes:
      label: What is the current bug behavior?
      description: A clear and concise description of what has happen.
    validations:
      required: true      
  - type: textarea
    id: expectedBehavior
    attributes:
      label: What is the expected correct behavior?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true 
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs and/or screenshots
      description: Paste any relevant logs and screenshots - use code blocks (```) to format console output, logs, and code, as it's very hard to read otherwise.
    validations:
      required: false 
  - type: textarea
    id: fix
    attributes:
      label: Possible fixes
      description: If you can, link to the line of code that might be responsible for the problem.
    validations:
      required: false 
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false