import { BLACK, BLUE0, BLUE3, GREY1, GREY2, GREY3, GREY5, RED, WHITE } from "../../constants";

//# Background Colors
//+ Navbar itself
export const LIGHT_NAV_BACKGROUND_COLOR = WHITE;
export const DARK_NAV_BACKGROUND_COLOR = GREY5;

//+ Tabs
export const LIGHT_NAV_TAB_BACKGROUND_MAIN_COLOR = WHITE;
export const DARK_NAV_TAB_BACKGROUND_MAIN_COLOR = "";

export const LIGHT_NAV_TAB_BACKGROUND_HOVER_COLOR = GREY1;
export const DARK_NAV_TAB_BACKGROUND_HOVER_COLOR = "";

export const LIGHT_NAV_TAB_BACKGROUND_ACTIVE_COLOR = GREY1;
export const DARK_NAV_TAB_BACKGROUND_ACTIVE_COLOR = "";

//+ Groups
export const LIGHT_NAV_GROUP_BACKGROUND_MAIN_COLOR = LIGHT_NAV_BACKGROUND_COLOR;
export const DARK_NAV_GROUP_BACKGROUND_MAIN_COLOR = "";

export const LIGHT_NAV_GROUP_BACKGROUND_HOVER_COLOR = GREY2;
export const DARK_NAV_GROUP_BACKGROUND_HOVER_COLOR = "";

export const LIGHT_NAV_GROUP_BACKGROUND_ACTIVE_COLOR = GREY2;
export const DARK_NAV_GROUP_BACKGROUND_ACTIVE_COLOR = "";

//+ Grouped Tabs
export const LIGHT_NAV_BACKGROUND_INSIDE_ACTIVE_GROUP_COLOR = GREY1;
export const DARK_NAVBAR_BACKGROUND_INSIDE_ACTIVE_GROUP_COLOR = "";

//# Font colors
//+ Tabs
export const LIGHT_NAV_TAB_FONT_MAIN_COLOR = BLUE0;
export const DARK_NAV_TAB_FONT_MAIN_COLOR = WHITE;

export const LIGHT_NAV_TAB_FONT_HOVER_COLOR = BLUE0;
export const DARK_NAV_TAB_FONT_HOVER_COLOR = WHITE;

export const LIGHT_NAV_TAB_FONT_ACTIVE_COLOR = BLUE0;
export const DARK_NAV_TAB_FONT_ACTIVE_COLOR = WHITE;

//+ Groups
export const LIGHT_NAV_GROUP_FONT_MAIN_COLOR = BLUE0;
export const DARK_NAV_GROUP_FONT_MAIN_COLOR = GREY3;

export const LIGHT_NAV_GROUP_FONT_HOVER_COLOR = BLUE0;
export const DARK_NAV_GROUP_FONT_HOVER_COLOR = WHITE;

export const LIGHT_NAV_GROUP_FONT_ACTIVE_COLOR = BLUE0;
export const DARK_NAV_GROUP_FONT_ACTIVE_COLOR = WHITE;

//# Icon colors
//+ Tab icons
export const LIGHT_NAV_TAB_ICON_MAIN_COLOR = BLUE0;
export const DARK_NAV_TAB_ICON_MAIN_COLOR = GREY3;

export const LIGHT_NAV_TAB_ICON_HOVER_COLOR = BLUE0;
export const DARK_NAV_TAB_ICON_HOVER_COLOR = WHITE;

export const LIGHT_NAV_TAB_ICON_ACTIVE_COLOR = BLUE0;
export const DARK_NAV_TAB_ICON_ACTIVE_COLOR = WHITE;

//+ Group icons
export const LIGHT_NAV_GROUP_ICON_MAIN_COLOR = BLUE0;
export const DARK_NAV_GROUP_ICON_MAIN_COLOR = GREY3;

export const LIGHT_NAV_GROUP_ICON_HOVER_COLOR = BLUE0;
export const DARK_NAV_GROUP_ICON_HOVER_COLOR = WHITE;

export const LIGHT_NAV_GROUP_ICON_ACTIVE_COLOR = BLUE0;
export const DARK_NAV_GROUP_ICON_ACTIVE_COLOR = WHITE;

//+ Group arrows
export const LIGHT_NAV_GROUP_ARROW_MAIN_COLOR = BLUE0;
export const DARK_NAV_GROUP_ARROW_MAIN_COLOR = GREY3;

export const LIGHT_NAV_GROUP_ARROW_HOVER_COLOR = RED;
export const DARK_NAV_GROUP_ARROW_HOVER_COLOR = WHITE;

export const LIGHT_NAV_GROUP_ARROW_ACTIVE_COLOR = RED;
export const DARK_NAV_GROUP_ARROW_ACTIVE_COLOR = WHITE;

//# Other
// Legal documents icon
export const LIGHT_NAV_LEGAL_DOCS_ICON_COLOR = BLUE3;
export const DARK_NAV_LEGAL_DOCS_ICON_COLOR = BLUE3;

export const LIGHT_NAV_SCROLLBAR_COLOR = GREY1;
export const DARK_NAV_SCROLLBAR_COLOR = GREY1;

// Color of navigation collapse arrow
export const LIGHT_NAV_COLLAPSE_ARROW_COLOR = BLACK;
export const DARK_NAV_COLLAPSE_ARROW_COLOR = GREY3;