import { BLACK, BLUE0, BLUE3, GREY1, GREY3, GREY5, WHITE } from "../../constants";

export const LIGHT_NAVBAR_BACKGROUND_COLOR = WHITE;
export const DARK_NAVBAR_BACKGROUND_COLOR = GREY5;

export const LIGHT_LEGAL_DOCS_ICON_COLOR = BLUE3;
export const DARK_LEGAL_DOCS_ICON_COLOR = BLUE3;

export const LIGHT_NAVBAR_COLLAPSE_ARROW_COLOR = BLACK;
export const DARK_NAVBAR_COLLAPSE_ARROW_COLOR = GREY3;

export const LIGHT_NAVBAR_SCROLLBAR_COLOR = GREY1;
export const DARK_NAVBAR_SCROLLBAR_COLOR = GREY1;

// For interface "TabColorType"
export const LIGHT_NAVBAR_MAIN_COLOR = WHITE;
export const DARK_NAVBAR_MAIN_COLOR = GREY5;

export const LIGHT_NAVBAR_HIGHLIGHT_COLOR = BLUE0;
export const DARK_NAVBAR_HIGHLIGHT_COLOR = GREY3;

export const LIGHT_NAVBAR_LETTERING_MAIN_COLOR = BLACK;
export const DARK_NAVBAR_LETTERING_MAIN_COLOR = GREY3;

export const LIGHT_NAVBAR_LETTERING_HIGHLIGHT_COLOR = WHITE;
export const DARK_NAVBAR_LETTERING_HIGHLIGHT_COLOR = WHITE;

export const LIGHT_NAVBAR_ICON_MAIN_COLOR = BLUE0;
export const DARK_NAVBAR_ICON_MAIN_COLOR = GREY3;

export const LIGHT_NAVBAR_ICON_HIGHLIGHT_COLOR = WHITE;
export const DARK_NAVBAR_ICON_HIGHLIGHT_COLOR = WHITE;

export const LIGHT_NAVBAR_ARROW_HIGHLIGHT_COLOR = WHITE;
export const DARK_NAVBAR_ARROW_HIGHLIGHT_COLOR = WHITE;

export const LIGHT_NAVBAR_ARROW_MAIN_COLOR = GREY3;
export const DARK_NAVBAR_ARROW_MAIN_COLOR = GREY3;